name: taskmanagerapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.2.2
  introduction_screen: ^3.1.14
  flutter_slidable: ^3.1.2
  intl: ^0.19.0
  percent_indicator: ^4.2.4
  fl_chart: ^0.69.2
  provider: ^6.1.2
  table_calendar: ^3.1.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.jpg
    - assets/images/profile.jpg
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
